global using Automaton.FeaturesSetup;
global using Automaton.FeaturesSetup.Attributes;
global using Automaton.IPC;
global using Automaton.Services;
global using Automaton.Utilities;
global using Automaton.Utilities.Extensions;
global using AutoRetainerAPI;
global using Dalamud.Game.Addon.Lifecycle;
global using Dalamud.Game.Addon.Lifecycle.AddonArgTypes;
global using Dalamud.Game.ClientState.Conditions;
global using Dalamud.Interface.Utility;
global using Dalamud.Plugin.Services;
global using ECommons.DalamudServices;
global using ECommons.GameHelpers;
global using ECommons.Logging;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Numerics;
global using static Automaton.Plugin;
global using static Automaton.Utilities.Enums;
global using static ECommons.GenericHelpers;
global using AtkValueType = FFXIVClientStructs.FFXIV.Component.GUI.ValueType;
global using CSGameObject = FFXIVClientStructs.FFXIV.Client.Game.Object.GameObject;
global using DGameObject = Dalamud.Game.ClientState.Objects.Types.IGameObject;
global using Sheets = Lumina.Excel.Sheets;
global using Callback = ECommons.Automation.Callback;
